account/urls.py
from django.urls import path
from .views import user_login, user_signup

app_name = 'account'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', user_signup, name='register'),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap, ProductSitemap


sitemaps = {
    'posts': PostSitemap,
    'products': ProductSitemap,
}


app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('post/<int:id>/', views.PostDetailView.as_view(), name='post-detail'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('user-order/', views.UserOrderView.as_view(), name='user-order'),
    path('contact/', views.ContactUsView.as_view(), name='contact'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('product/<int:id>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

resturant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext_lazy as _

class CustomUserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, **extra_fields):
        if not phone_number:
            raise ValueError(_('The Phone Number field must be set'))
        user = self.model(phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self.create_user(phone_number, password, **extra_fields)

class CustomUser(AbstractBaseUser):
    full_name = models.CharField(max_length=100)
    phone_number = models.CharField(unique=True, max_length=15)
    password = models.CharField(max_length=128)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['full_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.phone_number

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    full_name = forms.CharField(label='نام و نام خانوادگی', max_length=100)

    class Meta:
        model = CustomUser
        fields = ('full_name', 'phone_number', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.full_name = self.cleaned_data['full_name']
        if commit:
            user.save()
        return user

    phone_number = forms.CharField(
        label='شماره تلفن'
    )

class CustomAuthenticationForm(AuthenticationForm):
    phone_number = forms.CharField(label='شماره تلفن')
    password = forms.CharField(label='رمز عبور', widget=forms.PasswordInput)

account/views.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        password = request.POST.get('password')

        user = authenticate(request, username=phone, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'خوش آمدید')
            return redirect('home:home')
        else:
            messages.error(request, 'نام کاربری یا رمز عبور اشتباه است.')

    return render(request, 'login.html')


@csrf_exempt
def user_signup(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')

        User = get_user_model()

        if User.objects.filter(phone_number=phone).exists():
            messages.error(request, 'این شماره موبایل قبلاً ثبت شده است.')
        else:
            user = User.objects.create(
                phone_number=phone,
                full_name=last_name,
                password=make_password(password)
            )
            messages.success(request, 'ثبت نام با موفقیت انجام شد. لطفاً وارد شوید.')
            login(request, user)
            return redirect('home:home')

    return render(request, 'register.html')

account/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>رستوران امیرخان | ورود به سایت</title>
    <style>
        body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.container {
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    width: 100%;
    max-width: 400px;
}

.login-form {
    display: flex;
    flex-direction: column;
}

.login-form h1 {
    margin-bottom: 20px;
    font-size: 24px;
    color: #333;
}

.login-form label {
    margin-bottom: 8px;
    font-size: 14px;
    color: #555;
}

.login-form input {
    margin-bottom: 20px;
    padding: 10px;
    font-size: 16px;
    border: 1px solid #ddd;
    border-radius: 4px;
}

.login-form button {
    padding: 10px;
    font-size: 16px;
    color: #fff;
    background-color: #007bff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

.login-form button:hover {
    background-color: #0056b3;
}

    </style>
</head>
<body>
    {% include 'message.html' %}
    <div class="container">
        <form class="login-form" action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
            <h1>ورود</h1>
            <label for="phone">شماره موبایل</label>
            <input type="tel" id="phone" name="phone" required>

            <label for="password">رمز عبور</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">ورود</button>
            <a href="{% url  'account:register' %}"><p>.برای ثبت نام اینجا کلیک کنید</p></a>
        </form>
    </div>
</body>
</html>

account/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>رستوران امیرخان | ثبت نام</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
        }

        .signup-form {
            display: flex;
            flex-direction: column;
        }

        .signup-form h1 {
            margin-bottom: 20px;
            font-size: 24px;
            color: #333;
        }

        .signup-form label {
            margin-bottom: 8px;
            font-size: 14px;
            color: #555;
        }

        .signup-form input {
            margin-bottom: 20px;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }

        .signup-form button {
            padding: 10px;
            font-size: 16px;
            color: #fff;
            background-color: #007bff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .signup-form button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    {% include 'message.html' %}
    <div class="container">
        <form class="signup-form" action="{% url 'account:register' %}" method="post">
            {% csrf_token %}
            <h1>ثبت نام</h1>
            <label for="phone">شماره موبایل</label>
            <input type="tel" id="phone" name="phone" required>

            <label for="last_name">نام خانوادگی</label>
            <input type="text" id="last_name" name="last_name" required>

            <label for="password">رمز عبور</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">ثبت نام</button>
            <a href="{% url  'account:login' %}"><p>.برای ورود اینجا کلیک کنید</p></a>

        </form>
    </div>
</body>
</html>