account/urls.py
from django.urls import path
from .views import user_login, user_signup

app_name = 'account'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', user_signup, name='register'),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap, ProductSitemap


sitemaps = {
    'posts': PostSitemap,
    'products': ProductSitemap,
}


app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('post/<int:id>/', views.PostDetailView.as_view(), name='post-detail'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('user-order/', views.UserOrderView.as_view(), name='user-order'),
    path('contact/', views.ContactUsView.as_view(), name='contact'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('product/<int:id>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

resturant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{% block title %} {% endblock %}</title>
    
	<!-- Stylesheet -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="canonical" href="https://www.amirkhan-complex.com/" />
<meta property="og:title" content="رستوران امیرخان - غذاهای سلامتی و طعم‌های خاص" />
<meta property="og:description" content="رستوران امیرخان، تجربه‌ای تازه از طعم‌های اصیل و غذاهای سلامتی! با مقالات متنوع درباره بهترین غذاهای سلامت‌محور و توصیه‌های تغذیه‌ای." />
<meta property="og:image" content="https://amirkhan-complex.com/media/img/bg.img/1.jpg" />
<meta property="og:url" content="https://www.amirkhan-complex.com/" />
<meta property="og:type" content="website" />

<body>

    {% include 'message.html' %}
<!-- ##### Header Area Start ##### -->
	<header class="header-area">

		<!-- Top Header Area -->
		<div class="top-header-area bg-img bg-overlay" style="background-image: url(/media/img/bg-img/header.jpg);">
			<div class="container h-100">
				<div class="row h-100 align-items-center justify-content-between">
					<div class="col-12 col-sm-6">
						<!-- Top Social Info -->
						<div class="top-social-info">
						</div>
					</div>
					<div class="col-12 col-sm-6 col-lg-5 col-xl-4">
						<!-- Top Search Area -->
						<div class="top-search-area">
							
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Logo Area -->
		<div class="logo-area">
			<a href="{% url 'home:home' %}"><h1>AMIRKHAN</h1></a>
		</div>

		<!-- Navbar Area -->
		<div class="bueno-main-menu" id="sticker">
			<div class="classy-nav-container breakpoint-off">
				<div class="container">
					<!-- Menu -->
					<nav class="classy-navbar justify-content-between" id="buenoNav">

						<!-- Toggler -->
<!--						<div id="toggler"><img src="../media/img/core-img/toggler.png" alt=""></div>-->

						<!-- Navbar Toggler -->
						<div class="classy-navbar-toggler">
							<span class="navbarToggler"><span></span><span></span><span></span></span>
						</div>

						<!-- Menu -->
						<div class="classy-menu">

							<!-- Close Button -->
							<div class="classycloseIcon">
								<div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
							</div>

							<!-- Nav Start -->
							<div class="classynav">
								<ul>
									<li><a href="{% url 'home:home' %}">خانه</a></li>
									<li><a href="{% url 'home:order' %}">ثبت سفارش</a></li>
									<li><a href="{% url 'home:post-list' %}">بلاگ</a></li>
									<li><a href="{% url 'home:contact' %}">تماس با ما</a></li>
								</ul>

								<!-- Login/Register -->
								<div class="login-area">
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'home:user-order' %}">  خوش آمدید{{ request.user.full_name }}</a>
                                    {% else %}
									<a href="{% url 'account:login' %}">ورود / عضویت</a>
                                    {% endif %}
								</div>
							</div>
							<!-- Nav End -->

						</div>
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- ##### Header Area End ##### -->


    {% block main %}
    {% endblock %}

    
	<!-- ##### Instagram Area Start ##### -->
	<div class="instagram-feed-area d-flex flex-wrap">
		<style>
			.instagram-feed-area {
    display: flex;
    flex-wrap: wrap;
    gap: 15px; /* فاصله بین تصاویر */
    justify-content: center; /* مرکز کردن تصاویر */
}

.single-instagram {
    position: relative;
    overflow: hidden;
    width: 150px; /* عرض ثابت برای هر تصویر */
    height: 150px; /* ارتفاع ثابت برای هر تصویر */
}

.single-instagram img {
    width: 100%;
    height: 100%;
    object-fit: cover; /* برای برش مناسب تصاویر به اندازه باکس */
    transition: transform 0.3s ease; /* برای افکت زوم نرم */
}

.single-instagram:hover img {
    transform: scale(1.1); /* زوم شدن تصویر هنگام هاور */
}

.img-zoom {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: rgba(0, 0, 0, 0.5); /* پس‌زمینه نیمه‌شفاف */
    color: white;
    font-size: 24px;
    padding: 10px;
    border-radius: 50%;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.single-instagram:hover .img-zoom {
    opacity: 1; /* نمایش آیکن زوم هنگام هاور */
}

		</style>
		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta1.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta1.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta2.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta2.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta3.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta3.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta4.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta4.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta5.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta5.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta6.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta6.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta7.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta7.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta8.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta8.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta9.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta9.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>

		<!-- Single Instagram -->
		<div class="single-instagram">
			<img src="/media/img/bg-img/insta10.jpg" alt="insta1">
			<!-- Image Zoom -->
			<a href="/media/img/bg-img/insta10.jpg" class="img-zoom" title="پست اینستاگرام">+</a>
		</div>
	</div>
	<!-- ##### Instagram Area End ##### -->


    
	<!-- ##### Footer Area Start ##### -->
	<footer class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-12 ">
					<!-- Copywrite Text -->
					<p class="copywrite-text"><a href="#"></a></p>
					<p class="copywrite-text"><a href="#"></a><strong>ساخته شده با ❤️ توسط تیم فالکن</strong></p>
				</div>
			</div>
		</div>
	</footer>
	<!-- ##### Footer Area Start ##### -->

	<!-- ##### All Javascript Script ##### -->
	<!-- jQuery-2.2.4 js -->
	<script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
<!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Custom js -->
    <script  src="{% static 'js/scripts.js' %}"></script>

<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Restaurant",
    "name": "رستوران امیرخان",
    "image": "https://www.amirkhan-complex.com/media/img/bg-img/1.jpg",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "خیابان اصلی، کوچه شماره ۲",
        "addressLocality": "تهران",
        "postalCode": "123456",
        "addressCountry": "IR"
    },
    "telephone": "+9821-12345678",
    "priceRange": "$$",
    "servesCuisine": "ایرانی، سلامت‌محور",
    "url": "https://www.amirkhan-complex.com"
}
</script>

</body>
</html>

templates/loading.html
<!-- Preloader -->
<div class="preloader d-flex align-items-center justify-content-center">
	<div class="preloader-content">
		<h3>در حال بارگزاری..</h3>
		<div id="cooking">
			<div class="bubble"></div>
			<div class="bubble"></div>
			<div class="bubble"></div>
			<div class="bubble"></div>
			<div class="bubble"></div>
			<div id="area">
				<div id="sides">
					<div id="pan"></div>
					<div id="handle"></div>
				</div>
				<div id="pancake">
					<div id="pastry"></div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>پیام‌ها</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
        }

        .message-container {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 9999;
        }

        .message {
            padding: 10px 20px;
            margin-bottom: 10px;
            border-radius: 5px;
            color: #fff;
            opacity: 1;
            transition: opacity 0.5s ease;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        }

        .message.success { background-color: #28a745; }
        .message.error { background-color: #dc3545; }
        .message.info { background-color: #17a2b8; }
        .message.warning { background-color: #ffc107; color: #212529; }

        .message.fade-out {
            opacity: 0;
        }
    </style>
</head>
<body>
    <div class="message-container">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const messages = document.querySelectorAll('.message');
            messages.forEach(function(message) {
                setTimeout(() => {
                    message.classList.add('fade-out');
                    setTimeout(() => message.remove(), 500); // مطمئن شویم که پیام بعد از فید شدن حذف می‌شود
                }, 3000); // ۳ ثانیه بعد فید می‌شود
            });
        });
    </script>
</body>
</html>